// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOEj9Vh3SPSv380Z93MquhOAQYZ16eZZg',
    appId: '1:701180234225:web:4b521d951aea1f87265c50',
    messagingSenderId: '701180234225',
    projectId: 'veterann',
    authDomain: 'veterann.firebaseapp.com',
    storageBucket: 'veterann.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVTly7VPB6jZTtmk2kJYKp9ywldj6jj8g',
    appId: '1:701180234225:android:fe8dd1d9a6798611265c50',
    messagingSenderId: '701180234225',
    projectId: 'veterann',
    storageBucket: 'veterann.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4cVgMtuAL_G3aE95VFi1Rzo8raP2slhQ',
    appId: '1:701180234225:ios:0a69febf5d04995a265c50',
    messagingSenderId: '701180234225',
    projectId: 'veterann',
    storageBucket: 'veterann.firebasestorage.app',
    iosBundleId: 'com.example.veteranns',
  );
}
